### ISSUE TITLE
Query Optimization Assignment 6

### ISSUE THREAD

**Issue by ahmedhamdi96** [ila/TUM#8]
Shouldn't MVP consider incoming edges? Why is this solution considering outgoing edges instead?

**Comment by ahmedhamdi96** [comment]
For MVP, I think the costs are not calculated correctly too. Shouldn't it be the cost of (predecessor node + cost of 2 merged nodes)? It is calculated as (predecessor node + successor node + cost of 2 merged nodes).

**Comment by ila** [comment]
honestly, MVP still does not make any sense to me, and the author of this assignment did not include their names. do you want to make a PR with your solution? also it would be useful to see how many points you got, since this one should be 10/10

**Comment by ahmedhamdi96** [comment]
i didn't do the assignments :upside_down_face:
